[programs.localnet]
riddle_app = "BRgx1ATbc2rP9ge3k2RyCi3RWxNzbaqaveeSCeX8ZzhT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ixmorrow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
